### ISSUE TITLE
Support uploading to Codecov

### ISSUE THREAD

**Issue by FledgeXu** [openzim/_python-bootstrap#1]
Since we use the Codecov to track the coverage of the project. Maybe we want to enable it in all python projects?

**Comment by rgaudin** [comment]
Did you have anything else in mind that we'd do for codecov?

**Comment by FledgeXu** [comment]
Not really, maybe be add it to the CI?

**Comment by rgaudin** [comment]
It's already in the CI

https://github.com/openzim/_python-bootstrap/blob/a014fbec1101ae4374b526e4a56fe5a34eb3ab73/.github/workflows/Tests.yaml#L33-L39

**Comment by FledgeXu** [comment]
Ah, I missed it. Thanks.
