### ISSUE TITLE
Use `debugpy` as the Debug Adapter Protocol tools.

### ISSUE THREAD

**Issue by FledgeXu** [openzim/_python-bootstrap#10]
[debugpy](https://github.com/microsoft/debugpy) is a convenient tool that let all the text editors which support DAP can debug the Python program. Since we will inevitably use a virtual environment, I propose that we add `debugpy` to `dev` to facilitate debugging.

**Comment by rgaudin** [comment]
I've never used it ; I'm too old school but I just tested it with VSCode… my editor's plugin seems broken.
It works great!

As too whether to add it to the bootstrap of test it in a project, I have no opinion. I think it's no harm to have it. @benoit74 ?

**Comment by benoit74** [comment]
I think it's no harm either, I'm ok with the fact that we add it

**Comment by FledgeXu** [comment]
Ok, I will create a PR then.On Jul 16, 2023, at 1:42 PM, benoit74 ***@***.***> wrote:﻿
I think it's no harm either, I'm ok with the fact that we add it
