### ISSUE TITLE
Rethink the default `Ruff` Rules.

### ISSUE THREAD

**Issue by FledgeXu** [openzim/_python-bootstrap#14]
For now, the default Ruff rules are not suitable for every Python project we work on.  For example, in the FastAPI project, we should exclude the `A003`([Reason](https://github.com/openzim/nautilus-webui/pull/27#discussion_r1265576632)) and the `B008`([Reason](https://github.com/tiangolo/fastapi/issues/1522)). However, for the Python projects that don't use the FastAPI, we can still keep these two rules.
We should rethink which rules are appropriate for each Python project.

**Comment by rgaudin** [comment]
Well I think each rule (or set of rule) should be discussed individually, in the repo a change is needed and/or here in the bootstrap.

Workflow being:
- We a have set of rule that is a copy of another project's. It's untested yet and is a starting point.
- Now and in the future, no rule is set in stone. Those rules' goal is to ease our work. Either immediately or in the future by preventing potential issues resulting from less-quality code.
- bootstrap represents the _up-to-date, default, starting point_ for new projects
- repos are allowed to customize this set of rules to their own needs.
- developers should _backport_ to bootstrap rule changes when they see a general fit.

**Comment by rgaudin** [comment]
Closing in favor of #15 and #16
