### ISSUE TITLE
Remove flake8-errmsg

### ISSUE THREAD

**Issue by rgaudin** [openzim/_python-bootstrap#17]
All of [`flake8-errmsg`](https://beta.ruff.rs/docs/rules/#flake8-errmsg-em)'s rules are annoying and bloats the source code while their benefit is really minimal in my opinion.

The idea behind the 3 rules is that in an exception's log, there would be two lines for a single raise call instead of just one.

I propose to not use `flake8-errmsg` at all.

**Comment by benoit74** [comment]
I found the added value pretty small as well. The exception message is a little less verbose but at the same time the code is significantly more verbose and pushes forward the idea that it is fine to declare a new variable and use it only once, which I already tend to do too often 😄 

I'm ok with the fact that we remove `flake8-errmsg`
