### ISSUE TITLE
Add a Dockerfile + release workflow

### ISSUE THREAD

**Issue by benoit74** [openzim/_python-bootstrap#19]
A sample Dockerfile which builds / installs the project in an image would be welcomed, even if not relevant for few library projects, most projects are either scrapers or applications that need to be Dockerized.
The accompanying Github workflow must also be provided.

**Comment by rgaudin** [comment]
Right ; I wasn't sure at first but it's good to have a sample for this as well  as the accompanying workflow

**Comment by benoit74** [comment]
Fixed with #22
