### ISSUE TITLE
Enhance Docker usage

### ISSUE THREAD

**Issue by benoit74** [openzim/_python-bootstrap#23]
I suggest that we :
- add the build of the Docker image in the `Tests` workflow has to be added, because otherwise we might find that Docker image build is KO only after a release, which is a bit too late.
- have three separate jobs in the `Tests` workflow since they can run in parallel : `run-tests`, `test-build-python`, `test-build-docker`
- add a `Publish Docker dev image` workflow which is triggered manually to publish a `dev` tag, so that one can build it easily, and test how it behaves. This workflow must be manual because otherwise we could have conflicts on the `dev` tag

**Comment by rgaudin** [comment]
- We wouldn't need it if we kept the `:dev` tag build on commits on `main`. We can restore that ; not sure if _Tests_ is appropriate.
- `dev` should represent `main`, as we do for all projects (consistency). Developers are allowed to push arbitrary tags for tests –in the farm for instance– (and should take care of removal once obsolete).

**Comment by benoit74** [comment]
Is this ok for the last point then (I understand that you agree on the two firsts):
- add a `Public Docker dev image` worfklow (not `Tests`) which is triggered on pushes to main branch ; this workflow will build and publish `dev` image, which represents `main`

**Comment by rgaudin** [comment]
Yes ; can also be in tests, with the different jobs, if we consider this `dev` image a docker build test. Both are fine.
