### ISSUE TITLE
Create an openzim hatch plugin

### ISSUE THREAD

**Issue by benoit74** [openzim/_python-bootstrap#35]
We should create a hatch plugin which would:
- populate shared metadata, e.g. author, readme, license, classifiers, most keywords are expected to always be the same across all scrapers, it is a pain to repeat them over and over (with a significant risk of discrepancies / errors, and useless added complexity to update them all)
- propose some shared build actions, with the first known need being the "installation" of JS dependencies

Some known "good" plugins are listed here: https://hatch.pypa.io/latest/plugins/build-hook/reference/

Is it ok to name the plugin "hatch-openzim" and create a repo with the same name in the openzim organization?

**Comment by rgaudin** [comment]
> Is it ok to name the plugin "hatch-openzim" and create a repo with the same name in the openzim organization?

👍

**Comment by benoit74** [comment]
Work has started here: https://github.com/openzim/hatch-openzim/tree/initial_version

I struggle to test the plugin locally, probably only a misconfiguration, I asked for help [upstream](https://github.com/pypa/hatch/issues/1173).

Code for the download of assets is mostly ready, it only need a good test harness (and it is not really very simple to do locally, but still mandatory for such an important piece of code)

**Comment by benoit74** [comment]
Fixed by https://github.com/openzim/_python-bootstrap/pull/36
