### ISSUE TITLE
Disable pyright bytes type promotions

### ISSUE THREAD

**Issue by benoit74** [openzim/_python-bootstrap#37]
We should add `disableBytesTypePromotions = true` to pyright configuration in pyproject.toml (see https://github.com/openzim/warc2zim/commit/baafc7509312e94b4248cb19b56d652396d66577 for instance)

See [pyright documentation](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) and [PEP 688](https://peps.python.org/pep-0688/#no-special-meaning-for-bytes). I don't know why the legacy behavior is the default Pyright configuration.

@rgaudin WDYT?

**Comment by rgaudin** [comment]
I don't understand either why they default to `false`. That's might be a transition. We should thus set it to `true` 👍
