### ISSUE TITLE
Use pyright “basic” mode for older projects

### ISSUE THREAD

**Issue by benoit74** [openzim/_python-bootstrap#5]
In our policy, we state that for old projects, _"Static Type checking is not expected and should be removed"_.

While [migrating `kolibri` to this new standard](https://github.com/openzim/kolibri/pull/47), I realize this is probably wrong for two reasons:
- `ruff` is not capable to spot many very important/naive issues, like missing arguments in a function call (this is due to its nature, it does not interpret the code, so this is normal)
- `pyright` has a `typeCheckingMode` parameter which can be set to `basic` and provides many hints around code which obviously is wrong / won't run, all without bothering about advanced type features we won't be able to cope easily with on old projects (type hints everywhere, ...)

I suggest that we recommend to activate `pyright` in `basic` mode on all projects.

**Comment by benoit74** [comment]
I believe this only has to be reflected in the Wiki.

**Comment by rgaudin** [comment]
Sounds good. Can you update the Wiki and share the link (there's no notification on Wiki updates I believe)

> I suggest that we recommend to activate pyright in basic mode on all projects.

You mean in **older** projects right? We are still targeting `strict` for new ones.

**Comment by benoit74** [comment]
I propose to rephrase the wiki [Policy page](https://github.com/openzim/_python-bootstrap/wiki/Policy) like below. 

It was not the original topic of this issue but I propose to also change the statement regarding `ruff` rules, because from my experience many rules are raising very valid points so I would prefer that:
1. we fix what is reasonable
1. we add `# noqa: xxx` comments when it is not easily fixable
1. we disable whole rules / groups of rules only as a last resort, because it means that the situation might continue to get worse without us noticing it

Before:
```
- Requirements for older projects are relaxed:
  - Static Type checking is not expected and should be removed
  - Ruff rules should be commented to allow low-friction migration
  - Cython-using projects should continue with setuptools/setup.py

```

After:
```
- Requirements for older projects are relaxed:
  - Static Type Checking:
    - `pyright` mode might be set to `basic` (with the `typeCheckingMode` parameter)
    - few `# pyright: ignore` comments are allowed in the code
  - Ruff rules:
    - `# noqa: xxx` comments can be placed when necessary
    - as a last resort (because it means that the situation might continue to get worse), some rule or groups might be completely commented in `pyproject.toml`
  - Cython-using projects should continue with setuptools/setup.py
```

@rgaudin, ok for you?

**Comment by benoit74** [comment]
Plus `ruff` is automatically fixing many things.

**Comment by rgaudin** [comment]
Yes ; works for me.

**Comment by benoit74** [comment]
Done in wiki.
