### ISSUE TITLE
Worflows are not running when pushing to a branch without a pull request

### ISSUE THREAD

**Issue by benoit74** [openzim/_python-bootstrap#8]
When pushing to a branch (not `main`, any other branch), QA and Test workflows are not running.

This is a bit sad because it means that we must open a pull request to see workflows running and their result.

At the same time, if we activate workflows on all push and pull requests, it means that workflows will run twice in many cases.

I have identified an alternative ([implemented in `offspot/metrics` for instance](https://github.com/offspot/metrics/tree/main/.github/workflows)):
- run on pull requests only if source branch is from a fork (so that pull requests originating from a fork also start workflows)
- run on push on all branches of the current repo (so that workflows are started even when there is not - yet - a PR)

To make it works, we have to perform a `workflow call`, but it works well. 

WDYT ?

**Comment by benoit74** [comment]
@kelson42 could we quickly have your feedback on this proposal? 

We need to make a decision, both alternatives are ok for me, but we now have lots of variants between old way of doing this, new convention which is not deployed everywhere, my proposition which has been implemented in some cases before the convention was decided and this is not confortable.

**Comment by kelson42** [comment]
> 

Sorry for my lack of feedback.

This is something we have fixed a certain way everywhere the same manner. Look at https://github.com/openzim/libzim/blob/66b3b7f1de7f9ce1370de388e51364f420fc63e4/.github/workflows/ci.yml#L3 for example

@benoit74 Let me know if there anything you are not satified by this way of doing.

**Comment by benoit74** [comment]
Like I said before, I'm ok with this way of doing.

I personally find it more elegant to start workflows as soon as a push occurs rather than relying on pull requests being opened, but I agree this is a very personal taste not backed by a lot of science / arguments. 

The purpose of this issue was to ensure that we are all aligned on the way of doing things, and that we were doing it on purpose (i.e. not only because "otherwise the workflows will twice on some cases"), because as of today, we are not (yet) doing this everywhere the same manner.

I'm ok with the decision to stick with the fact that we run workflows on pull requests + push on `main` branch as coded today in the bootstrap workflows.

**Comment by kelson42** [comment]
@benoit74 Thx, I believe we discussed that already in details?! So concretly, you have to make (draft) PRs to get the CI running. This is IMO the main and only advantage/disadvantage.
